apiVersion: apps/v1
kind: Deployment 
metadata:
  name: first-app
  labels:
    app: first-app
spec:
  selector:
    matchLabels:
      app: first-app
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
      - name: first-app
        image: first-app:1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
  
---

apiVersion: v1
kind: Service
metadata:
  name: first-app
spec:
  type: NodePort
  selector:
    app: first-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001