apiVersion: apps/v1
kind: Deployment
metadata:
  name: secondapp
  labels:
    app: secondapp
spec:
  selector:
    matchLabels:
      app: secondapp
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: secondapp
    spec:
      containers:
      - name: secondapp
        image: secondapp:1
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 8081

--- 
apiVersion: v1
kind: Service
metadata:
  name: secondapp
spec:
  selector:
    app: secondapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
    nodePort: 30002